name: "ER Diagram"
on:
  push:
    branches: [ "main" ]
    # paths:
    #   - "db/migrate/**"
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DB_NAME: myapp_test
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: root
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          ruby-version: 3.1.3
          bundler-cache: true
      - name: Bundler and gem install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: Database create and migrate
        run: |
          cp config/database.ci.yml config/database.yml
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test
      - name: Make schemaspy.properties
        run: |
          echo -e "
          schemaspy.t=mysql\n
          schemaspy.dp=\n
          schemaspy.host=db\n
          schemaspy.port=3306\n
          schemaspy.db=$DB_NAME\n
          schemaspy.u=root\n
          schemaspy.p=password\n
          schemaspy.o=\n
          schemaspy.s=$DB_NAME\n
          " > /tmp/schemaspy.properties
      - name: Prepare a dir for schemaspy output
        run: mkdir -m 777 /tmp/output
      - name: Run schemaspy
        run: docker run --net=${{ job.container.network }} -v "/tmp/output:/output" -v "/tmp/schemaspy.properties:/schemaspy.properties" schemaspy/schemaspy:latest -rails
      - name: Upload ER Diagram
        uses: actions/upload-pages-artifact@v1
        with:
          path: /tmp/output
  deploy:
    needs: generate
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
